### ISSUE TITLE
Parsing issue

### ISSUE THREAD

**Issue by SmileForTheInternet** [ChapelR/dice-notation#4]
When using a command in discord.js !roll and passing in an arg like 3d20 or 4d10 are ignoring the zeros and only rolling it as a 2 or 1 in these cases. From using the npm install functions

**Comment by ChapelR** [comment]
You sure this is the right repository? This software is available on NPM but I'm not sure how it integrates with discord, I'm pretty sure some discord APIs would have to be added for that. Did you add these yourself?

**Comment by SmileForTheInternet** [comment]
Yeah connecting to discord is fine and all from using it to teach myself
javascript but the input to the dice function isn't the same as the
detailed.result and the dice.detailed() is also not recognizing a dice that
ends in zero. [image: image.png][image: image.png]

**Comment by SmileForTheInternet** [comment]
![image](https://user-images.githubusercontent.com/38746017/103486893-3ce2d600-4dcf-11eb-98ea-bbf46783a827.png)
![image](https://user-images.githubusercontent.com/38746017/103486898-42402080-4dcf-11eb-86c1-c225e91d9e2b.png)
these are the images that failed to come thru the email

**Comment by ChapelR** [comment]
Thanks, it should be fixed now.
